kind: pipeline
type: docker
name: default

steps:
  - name: web tests
    image: adoptopenjdk/maven-openjdk11
    commands:
       - mvn test -Dtest=PropertiesDaoTest -DfailIfNoTests=false
       - mvn test -Dtest=WebObjectFactoryTest -DfailIfNoTests=false
  - name: client tests
    image: adoptopenjdk/maven-openjdk11
    commands:
       - mvn test -Dtest=BankClientTest -DfailIfNoTests=false
       - mvn test -Dtest=JsonDtoTests -DfailIfNoTests=false
       - mvn test -Dtest=PasswordUtilsTest -DfailIfNoTests=false
  - name: general tests
    image: adoptopenjdk/maven-openjdk11
    commands:
       - mvn --batch-mode --update-snapshots -DskipTests=true verify
